title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options root=UUID=03b5c761-b41f-4279-b854-34aacaa80ba7 rootflags=subvol=/@ resume=UUID=f72bc451-31d5-41a2-a531-7bec6b204a48 rw quiet splash fbcon=nodefer
